<a href="https://colab.research.google.com/github/sac-1999/PyTorch100/blob/main/Autograd_%26_backPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Custom Autograd & Backpropagation (10) Build a custom autograd function for ReLU.

In [2]:
import torch

In [3]:
class square_f(torch.autograd.Function):
  @staticmethod
  def forward(ctx, x):
    ctx.save_for_backward(x)
    return x**2
  @staticmethod
  def backward(ctx, grad_output):
    print('--------', ctx.saved_tensors)
    print(grad_output)
    (x,) = ctx.saved_tensors
    return 2*x * grad_output


In [9]:
class cube_f(torch.autograd.Function):
  @staticmethod
  def forward(cxt, x):
    cxt.save_for_backward(x)
    return x**3

  @staticmethod
  def backward(cxt, grad_output):
    (x, ) = cxt.saved_tensors
    return 3*x*grad_output


In [10]:
x = torch.arange(1,10, 1,dtype=torch.float32, requires_grad = True)
y = square_f.apply(x)
y2 = cube_f.apply(y)

In [11]:
y, y2, x

(tensor([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
        grad_fn=<square_fBackward>),
 tensor([1.0000e+00, 6.4000e+01, 7.2900e+02, 4.0960e+03, 1.5625e+04, 4.6656e+04,
         1.1765e+05, 2.6214e+05, 5.3144e+05], grad_fn=<cube_fBackward>),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], requires_grad=True))

In [12]:
y2.backward(torch.ones(1,9).squeeze())

-------- (tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], requires_grad=True),)
tensor([  3.,  12.,  27.,  48.,  75., 108., 147., 192., 243.])


In [13]:
x.grad

tensor([   6.,   48.,  162.,  384.,  750., 1296., 2058., 3072., 4374.])