<a href="https://colab.research.google.com/github/sac-1999/PyTorch100/blob/main/ElementWise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Implement element-wise operations without built-in functions.

In [1]:
import torch

In [39]:
mat1 = torch.randint(0,10, (1,3))
mat2 = torch.randint(0, 10, (3, 3))

In [34]:
mat1 * mat2

tensor([[32, 56,  9],
        [24,  8, 28],
        [72, 20, 45]])

In [41]:
mat1, mat2

(tensor([[3, 4, 7]]),
 tensor([[0, 4, 2],
         [6, 9, 0],
         [0, 7, 2]]))

In [37]:
def element_wise_multiplication(mat1, mat2):
  assert mat1.shape == mat2.shape
  mat3 = torch.randint(0, 10, mat1.shape)
  for i in range(mat1.shape[0]):
    for j in range(mat1.shape[1]):
      mat3[i][j] = mat1[i][j] * mat2[i][j]

  return mat3

element_wise_multiplication(mat1, mat2)


tensor([[32, 56,  9],
        [24,  8, 28],
        [72, 20, 45]])

In [40]:
torch.mul(mat1, mat2)

tensor([[ 0, 16, 14],
        [18, 36,  0],
        [ 0, 28, 14]])

In [ ]:
#repeat, expand, view clear