<a href="https://colab.research.google.com/github/sac-1999/PyTorch100/blob/main/Normalize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Write a function to normalize tensors (min-max scaling).

In [34]:
import torch

In [37]:
mat = torch.randint(0,10, (3,3))
mat

tensor([[3, 9, 8],
        [7, 7, 4],
        [4, 2, 0]])

In [46]:
def noramlize(t):
  max = torch.max(t)
  min = torch.min(t)
  updated_t = (t - min)/(max - min)
  return updated_t

noramlize(mat)

tensor([[0.3333, 1.0000, 0.8889],
        [0.7778, 0.7778, 0.4444],
        [0.4444, 0.2222, 0.0000]])

In [54]:
# column wise normalization
def normalize_by_columns(t):
  max = t.max(dim = 1).values
  min = t.min(dim = 1).values
  updated_t = (t - min)/(max - min )
  return updated_t

normalize_by_columns(mat)

tensor([[ 0.0000,  1.6667,  2.0000],
        [ 0.6667,  1.0000,  1.0000],
        [ 0.1667, -0.6667,  0.0000]])